# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI for RecourceCentre

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: ant -noinput -buildfile ResourceCentre/build.xml
    - name: Compile JUnit Test
      run: javac -cp ResourceCentre/bin:ResourceCentre/ant/junit.jar ResourceCentre/test/ResourceCentreTest.java -d ResourceCentre/bin
    - name: Run JUnit test
      run: java -jar ResourceCentre/ant/junit.jar --classpath ResourceCentre/bin --scan-class-path 
    - name: Test Execution
      run: java -cp ResourceCentre/bin ResourceCentre < ResourceCentre/user_input.txt
